const baseUrl =
  'https://res.cloudinary.com/thedrflynn/image/upload/v1589706435/portfolio/assets/screenshots';

export const projectList = [
  {
    src: `${baseUrl}/webp/naijaworks.webp`,
    dsrc: `${baseUrl}/original/naijaworks_p.png`,
    href: 'https://naijaworks.xyz',
    title: 'Naija Works',
    description: 'Intuitive showcase for Nigerian tech talents',
    stack: 'Built with: React ∙ Typescript ∙ Node ∙ GraphQL ∙ MongoDB',
    role: 'Backend',
    duration: '07 days',
    team: 3,
    codebase: 'https://github.com/NaijaWorks',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/pluto.webp`,
    dsrc: `${baseUrl}/original/pluto_p.png`,
    href: 'https://getpluto.netlify.com',
    title: 'Pluto',
    description: 'Create quizzes for your team. Get real-time progress updates',
    stack: 'Built with: React ∙ Redux ∙ Node ∙ Express ∙ PostgreSQL',
    role: 'Backend',
    duration: '12 days',
    team: 3,
    codebase: 'https://github.com/webeu3-pluto',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/anywherefitness.webp`,
    dsrc: `${baseUrl}/original/anywherefitness_p.png`,
    href: 'https://anywherelanding.now.sh/',
    title: 'Anywhere Fitness',
    description: 'Schedule and discover fitness classes near you',
    stack: 'Built with: React ∙ Node ∙ Express ∙ PostgreSQL',
    role: 'Teamlead',
    duration: '05 days',
    team: 7,
    codebase: 'https://github.com/BW-Anywhere-Fitness-Nov-18-22',
    mobileReady: false
  },
  {
    src: `${baseUrl}/webp/soupkitchen.webp`,
    dsrc: `${baseUrl}/original/soupkitchen_p.png`,
    href: 'https://skim.netlify.com',
    title: 'Soup Kitchen',
    description: 'Inventory management for soup kitchen owners',
    stack: 'Built with: React ∙ Redux ∙ Styled Components',
    role: 'Frontend',
    duration: '05 days',
    team: 1,
    codebase: 'https://gitlab.com/josenriagu/soup-kitchen-inventory',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/refugeestories.webp`,
    dsrc: `${baseUrl}/original/refugeestories_p.png`,
    href: 'https://bwrefugeestories.now.sh',
    title: 'Refugee Stories',
    description:
      'Collection of Refugee stories. Get inspired to volunteer in an aid',
    stack: 'Built with: React ∙ Redux ∙ Node ∙ Express ∙ PostgreSQL',
    role: 'Teamlead',
    duration: '05 days',
    team: 5,
    codebase: 'https://github.com/BW-Refugee-Stories-Oct-21-25',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/lambdagram.webp`,
    dsrc: `${baseUrl}/original/lambdagram_p.png`,
    href: 'https://lambdagram.netlify.com',
    title: 'Instagram Clone',
    description: "Intuitive clone of Instagram UI using React's HOC",
    stack: 'Built with: React ∙ Styled Components',
    role: 'Frontend',
    duration: '04 days',
    team: 1,
    codebase: 'https://github.com/josenriagu/React-Insta-Clone',
    mobileReady: false
  },
  {
    src: `${baseUrl}/webp/chefportfolio.webp`,
    dsrc: `${baseUrl}/original/chefportfolio_p.png`,
    href: 'https://bwchefportfolio.now.sh',
    title: 'Chef Portfolio',
    description:
      'Draw inspirations from portfolios of best chefs in your locality',
    stack: 'Built with: React ∙ Redux ∙ Node ∙ Express ∙ PostgreSQL',
    role: 'Teamlead',
    duration: '05 days',
    team: 7,
    codebase: 'https://github.com/BW-Refugee-Stories-Oct-21-25',
    mobileReady: false
  },
  {
    src: `${baseUrl}/webp/chargescreen.webp`,
    dsrc: `${baseUrl}/original/chargescreen_p.png`,
    href: 'https://chargescreen.netlify.coom',
    title: 'OneUI Charge screen',
    description: 'Inspired by the interactive charge screen of Samsung OneUI',
    stack: 'Built with: React',
    role: 'Frontend',
    duration: '0.1 days',
    team: 1,
    codebase: 'https://github.com/josenriagu/chargescreen',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/paltreev.webp`,
    dsrc: `${baseUrl}/original/paltreev_j.jpg`,
    href: 'https://paltreev.com',
    title: 'Paltreev',
    description: 'Location-based skill sharing and businesss discovery network',
    stack: 'Built with: HTML ∙ CSS ∙ JQuery ∙ PHP',
    role: 'Frontend',
    duration: '9+ days',
    team: 2,
    codebase: '',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/royalgatsby.webp`,
    dsrc: `${baseUrl}/original/royalgatsby_j.jpg`,
    href: 'https://royalgatsby.com',
    title: 'Royal Gatsby',
    description: 'E-commerce fashion store',
    stack: 'Built with: Self-hosted Wordpress',
    role: 'Designer',
    duration: '03 days',
    team: 1,
    codebase: '',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/nkutheatre.webp`,
    dsrc: `${baseUrl}/original/nkutheatre_j.jpg`,
    href: 'https://nkutheatre.com',
    title: 'Nku Theatre',
    description: 'Magazine blog',
    stack: 'Built with: Self-hosted Wordpress',
    role: 'Designer',
    duration: '1.5 days',
    team: 1,
    codebase: '',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/uberboytrend.webp`,
    dsrc: `${baseUrl}/original/uberboytrend_p.png`,
    href: 'https://uberboytrend.com',
    title: 'Uberboy Trend',
    description: 'E-commerce fashion store',
    stack: 'Built with: Self-hosted Wordpress',
    role: 'Designer',
    duration: '03 days',
    team: 1,
    codebase: '',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/flexushotels.webp`,
    dsrc: `${baseUrl}/original/flexushotels_j.jpg`,
    href: 'https://flexushotels.com',
    title: 'Flexus Hotels',
    description: 'Hotel booking management',
    stack: 'Built with: Self-hosted Wordpress',
    role: 'Designer',
    duration: '03 days',
    team: 1,
    codebase: '',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/mainmarket.webp`,
    dsrc: `${baseUrl}/original/mainmarket_j.jpg`,
    href: 'https://mainmarketonline.com',
    title: 'Mainmarket Online',
    description: 'Multi-vendor E-commerce store',
    stack: 'Built with: Self-hosted Wordpress',
    role: 'Designer',
    duration: '04 days',
    team: 1,
    codebase: '',
    mobileReady: true
  },
  {
    src: `${baseUrl}/webp/hubrisconsult.webp`,
    dsrc: `${baseUrl}/original/hubrisconsult_p.png`,
    href: 'https://hubrisconsult.com',
    title: 'Hubris Consult',
    description: 'Web design and digital marketing agency',
    stack: 'Built with: Self-hosted Wordpress',
    role: 'Designer',
    duration: '2.5 days',
    team: 1,
    codebase: '',
    mobileReady: true
  }
];
